page_title                                : Wordout

# App Info
ios_app_id                                : 1540450818

appstore_link                             : https://apps.apple.com/app/id1540450818

app_icon                                  : assets/appicon.png
app_name                                  : Wordout
app_price                                 : Free
app_description                           : Learn New Vocabularies & Play Word Puzzles

enable_smart_app_banner                   : true

instagram_username                        : wordoutio
twitter_username                          : wordoutio

features                                  :

  - title                                 : Learn New Vocabularies
    description                           : Improve your English by learning one new word daily.
    fontawesome_icon_name                 : book
    
  - title                                 : Personalized Experience
    description                           : Our powerful AI personalizes your experience as you use the app.
    fontawesome_icon_name                 : magic

  - title                                 : Words + Workout = Wordout
    description                           : Train your brain by solving daily puzzles while learning new words.
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Share & Challenge Your Friends
    description                           : Challenge your friends on social media by generating a word puzzle.
    fontawesome_icon_name                 : external-link-alt

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
